# Generated by Django 3.2.25 on 2024-04-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='usagefor',
            old_name='usage_for_name',
            new_name='usagefor_name',
        ),
    ]
